version: '3.7'

networks:
    backend:
        driver: bridge

volumes:
    bitnami:
        driver: local
    init:
        driver: local

services:
    postgres1:
        image: bitnami/postgres:12.2.0
        networks:
            - backend
        volumes:
            - ./data/bitnami:/bitnami
        environment:
            - MONGODB_ROOT_PASSWORD=apassword
            - MONGODB_USERNAME=easyStore
            - MONGODB_PASSWORD=easyStore
            - MONGODB_DATABASE=easyStore
    easyStore:
        image: 'scratch'
        depends_on: [postgres1]
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - httpPort=${httpPort}
        ports:
            - ${httpPort}:${httpPort}
        networks:
            - backend

    