version: '3.7'

networks:
    backend:
        driver: bridge

volumes:
    postgres1:
        driver: local
    init:
        driver: local
    phpmyadmin:
        driver: local

services:
    postgres1:
        image: bitnami/postgresql:12
        networks:
            - backend
        volumes:
            - ./data/postgres1:/bitnami/postgres
            - ./data/init/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRESQL_PASSWORD=apassword
    pgAdmin:
        image: dpage/pgadmin4:4
        depends_on:
            - postgres1
        networks:
            - backend
        ports:
            - 8081:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@example.com
            - PGADMIN_DEFAULT_PASSWORD=a
    easyStore:
        image: 'scratch'
        depends_on:
            - postgres1
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - backend
        ports:
            - ${httpPort}:${httpPort}
        environment:
            - httpPort=${httpPort}
    