version: '3.7'

services:
    bpbottemp:
        image: 'scratch'
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./indev.env
        ports:
            - 8080:8080